// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dcaccount_proto.proto

package account_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//注册用户登录到中心服
type LS_DC_ReqRegisterAccoutMsg struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientType           uint32   `protobuf:"varint,3,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	PhoneNum             uint32   `protobuf:"varint,4,opt,name=phone_num,json=phoneNum,proto3" json:"phone_num,omitempty"`
	ClientConnID         uint32   `protobuf:"varint,6,opt,name=client_connID,json=clientConnID,proto3" json:"client_connID,omitempty"`
	ClientIp             string   `protobuf:"bytes,7,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	MacAddr              string   `protobuf:"bytes,8,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`
	Version              uint32   `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LS_DC_ReqRegisterAccoutMsg) Reset()         { *m = LS_DC_ReqRegisterAccoutMsg{} }
func (m *LS_DC_ReqRegisterAccoutMsg) String() string { return proto.CompactTextString(m) }
func (*LS_DC_ReqRegisterAccoutMsg) ProtoMessage()    {}
func (*LS_DC_ReqRegisterAccoutMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_929ac4981a9b8677, []int{0}
}

func (m *LS_DC_ReqRegisterAccoutMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LS_DC_ReqRegisterAccoutMsg.Unmarshal(m, b)
}
func (m *LS_DC_ReqRegisterAccoutMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LS_DC_ReqRegisterAccoutMsg.Marshal(b, m, deterministic)
}
func (m *LS_DC_ReqRegisterAccoutMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LS_DC_ReqRegisterAccoutMsg.Merge(m, src)
}
func (m *LS_DC_ReqRegisterAccoutMsg) XXX_Size() int {
	return xxx_messageInfo_LS_DC_ReqRegisterAccoutMsg.Size(m)
}
func (m *LS_DC_ReqRegisterAccoutMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LS_DC_ReqRegisterAccoutMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LS_DC_ReqRegisterAccoutMsg proto.InternalMessageInfo

func (m *LS_DC_ReqRegisterAccoutMsg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LS_DC_ReqRegisterAccoutMsg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LS_DC_ReqRegisterAccoutMsg) GetClientType() uint32 {
	if m != nil {
		return m.ClientType
	}
	return 0
}

func (m *LS_DC_ReqRegisterAccoutMsg) GetPhoneNum() uint32 {
	if m != nil {
		return m.PhoneNum
	}
	return 0
}

func (m *LS_DC_ReqRegisterAccoutMsg) GetClientConnID() uint32 {
	if m != nil {
		return m.ClientConnID
	}
	return 0
}

func (m *LS_DC_ReqRegisterAccoutMsg) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *LS_DC_ReqRegisterAccoutMsg) GetMacAddr() string {
	if m != nil {
		return m.MacAddr
	}
	return ""
}

func (m *LS_DC_ReqRegisterAccoutMsg) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

//中心服返回登录服注册消息
type DC_LS_RespnRegisterAccoutMsg struct {
	ClientConnID         uint32   `protobuf:"varint,1,opt,name=client_connID,json=clientConnID,proto3" json:"client_connID,omitempty"`
	RestCode             int32    `protobuf:"varint,2,opt,name=rest_code,json=restCode,proto3" json:"rest_code,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ClientType           uint32   `protobuf:"varint,5,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DC_LS_RespnRegisterAccoutMsg) Reset()         { *m = DC_LS_RespnRegisterAccoutMsg{} }
func (m *DC_LS_RespnRegisterAccoutMsg) String() string { return proto.CompactTextString(m) }
func (*DC_LS_RespnRegisterAccoutMsg) ProtoMessage()    {}
func (*DC_LS_RespnRegisterAccoutMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_929ac4981a9b8677, []int{1}
}

func (m *DC_LS_RespnRegisterAccoutMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DC_LS_RespnRegisterAccoutMsg.Unmarshal(m, b)
}
func (m *DC_LS_RespnRegisterAccoutMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DC_LS_RespnRegisterAccoutMsg.Marshal(b, m, deterministic)
}
func (m *DC_LS_RespnRegisterAccoutMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DC_LS_RespnRegisterAccoutMsg.Merge(m, src)
}
func (m *DC_LS_RespnRegisterAccoutMsg) XXX_Size() int {
	return xxx_messageInfo_DC_LS_RespnRegisterAccoutMsg.Size(m)
}
func (m *DC_LS_RespnRegisterAccoutMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DC_LS_RespnRegisterAccoutMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DC_LS_RespnRegisterAccoutMsg proto.InternalMessageInfo

func (m *DC_LS_RespnRegisterAccoutMsg) GetClientConnID() uint32 {
	if m != nil {
		return m.ClientConnID
	}
	return 0
}

func (m *DC_LS_RespnRegisterAccoutMsg) GetRestCode() int32 {
	if m != nil {
		return m.RestCode
	}
	return 0
}

func (m *DC_LS_RespnRegisterAccoutMsg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DC_LS_RespnRegisterAccoutMsg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DC_LS_RespnRegisterAccoutMsg) GetClientType() uint32 {
	if m != nil {
		return m.ClientType
	}
	return 0
}

//用户登录到中心服验证
type LS_DC_ReqLoginMsg struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientType           uint32   `protobuf:"varint,3,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	ClientConnID         uint32   `protobuf:"varint,4,opt,name=client_connID,json=clientConnID,proto3" json:"client_connID,omitempty"`
	ClientIp             string   `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	MacAddr              string   `protobuf:"bytes,6,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`
	Version              uint32   `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LS_DC_ReqLoginMsg) Reset()         { *m = LS_DC_ReqLoginMsg{} }
func (m *LS_DC_ReqLoginMsg) String() string { return proto.CompactTextString(m) }
func (*LS_DC_ReqLoginMsg) ProtoMessage()    {}
func (*LS_DC_ReqLoginMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_929ac4981a9b8677, []int{2}
}

func (m *LS_DC_ReqLoginMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LS_DC_ReqLoginMsg.Unmarshal(m, b)
}
func (m *LS_DC_ReqLoginMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LS_DC_ReqLoginMsg.Marshal(b, m, deterministic)
}
func (m *LS_DC_ReqLoginMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LS_DC_ReqLoginMsg.Merge(m, src)
}
func (m *LS_DC_ReqLoginMsg) XXX_Size() int {
	return xxx_messageInfo_LS_DC_ReqLoginMsg.Size(m)
}
func (m *LS_DC_ReqLoginMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LS_DC_ReqLoginMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LS_DC_ReqLoginMsg proto.InternalMessageInfo

func (m *LS_DC_ReqLoginMsg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LS_DC_ReqLoginMsg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LS_DC_ReqLoginMsg) GetClientType() uint32 {
	if m != nil {
		return m.ClientType
	}
	return 0
}

func (m *LS_DC_ReqLoginMsg) GetClientConnID() uint32 {
	if m != nil {
		return m.ClientConnID
	}
	return 0
}

func (m *LS_DC_ReqLoginMsg) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *LS_DC_ReqLoginMsg) GetMacAddr() string {
	if m != nil {
		return m.MacAddr
	}
	return ""
}

func (m *LS_DC_ReqLoginMsg) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

//中心服返回登录服登录消息
type DC_LS_RespnLoginAccoutMsg struct {
	ClientConnID         uint32   `protobuf:"varint,1,opt,name=client_connID,json=clientConnID,proto3" json:"client_connID,omitempty"`
	RestCode             int32    `protobuf:"varint,2,opt,name=rest_code,json=restCode,proto3" json:"rest_code,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	AccountID            uint64   `protobuf:"varint,4,opt,name=accountID,proto3" json:"accountID,omitempty"`
	ClientType           uint32   `protobuf:"varint,5,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DC_LS_RespnLoginAccoutMsg) Reset()         { *m = DC_LS_RespnLoginAccoutMsg{} }
func (m *DC_LS_RespnLoginAccoutMsg) String() string { return proto.CompactTextString(m) }
func (*DC_LS_RespnLoginAccoutMsg) ProtoMessage()    {}
func (*DC_LS_RespnLoginAccoutMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_929ac4981a9b8677, []int{3}
}

func (m *DC_LS_RespnLoginAccoutMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DC_LS_RespnLoginAccoutMsg.Unmarshal(m, b)
}
func (m *DC_LS_RespnLoginAccoutMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DC_LS_RespnLoginAccoutMsg.Marshal(b, m, deterministic)
}
func (m *DC_LS_RespnLoginAccoutMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DC_LS_RespnLoginAccoutMsg.Merge(m, src)
}
func (m *DC_LS_RespnLoginAccoutMsg) XXX_Size() int {
	return xxx_messageInfo_DC_LS_RespnLoginAccoutMsg.Size(m)
}
func (m *DC_LS_RespnLoginAccoutMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DC_LS_RespnLoginAccoutMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DC_LS_RespnLoginAccoutMsg proto.InternalMessageInfo

func (m *DC_LS_RespnLoginAccoutMsg) GetClientConnID() uint32 {
	if m != nil {
		return m.ClientConnID
	}
	return 0
}

func (m *DC_LS_RespnLoginAccoutMsg) GetRestCode() int32 {
	if m != nil {
		return m.RestCode
	}
	return 0
}

func (m *DC_LS_RespnLoginAccoutMsg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DC_LS_RespnLoginAccoutMsg) GetAccountID() uint64 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *DC_LS_RespnLoginAccoutMsg) GetClientType() uint32 {
	if m != nil {
		return m.ClientType
	}
	return 0
}

//登录发送中心服离线
type LS_DC_ClientOffLineMsg struct {
	AccountID            uint64   `protobuf:"varint,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LS_DC_ClientOffLineMsg) Reset()         { *m = LS_DC_ClientOffLineMsg{} }
func (m *LS_DC_ClientOffLineMsg) String() string { return proto.CompactTextString(m) }
func (*LS_DC_ClientOffLineMsg) ProtoMessage()    {}
func (*LS_DC_ClientOffLineMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_929ac4981a9b8677, []int{4}
}

func (m *LS_DC_ClientOffLineMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LS_DC_ClientOffLineMsg.Unmarshal(m, b)
}
func (m *LS_DC_ClientOffLineMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LS_DC_ClientOffLineMsg.Marshal(b, m, deterministic)
}
func (m *LS_DC_ClientOffLineMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LS_DC_ClientOffLineMsg.Merge(m, src)
}
func (m *LS_DC_ClientOffLineMsg) XXX_Size() int {
	return xxx_messageInfo_LS_DC_ClientOffLineMsg.Size(m)
}
func (m *LS_DC_ClientOffLineMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LS_DC_ClientOffLineMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LS_DC_ClientOffLineMsg proto.InternalMessageInfo

func (m *LS_DC_ClientOffLineMsg) GetAccountID() uint64 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *LS_DC_ClientOffLineMsg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*LS_DC_ReqRegisterAccoutMsg)(nil), "account_proto.LS_DC_ReqRegisterAccoutMsg")
	proto.RegisterType((*DC_LS_RespnRegisterAccoutMsg)(nil), "account_proto.DC_LS_RespnRegisterAccoutMsg")
	proto.RegisterType((*LS_DC_ReqLoginMsg)(nil), "account_proto.LS_DC_ReqLoginMsg")
	proto.RegisterType((*DC_LS_RespnLoginAccoutMsg)(nil), "account_proto.DC_LS_RespnLoginAccoutMsg")
	proto.RegisterType((*LS_DC_ClientOffLineMsg)(nil), "account_proto.LS_DC_ClientOffLineMsg")
}

func init() { proto.RegisterFile("dcaccount_proto.proto", fileDescriptor_929ac4981a9b8677) }

var fileDescriptor_929ac4981a9b8677 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x86, 0x15, 0x08, 0x24, 0xf1, 0x86, 0x26, 0x22, 0x6d, 0x32, 0x0c, 0x69, 0x88, 0xdd, 0x70,
	0xc5, 0x2e, 0xf6, 0x04, 0x2c, 0xdc, 0x20, 0x65, 0x9b, 0x64, 0x7a, 0xd5, 0x1b, 0x2b, 0x8d, 0x0f,
	0x34, 0x52, 0x63, 0xbb, 0x76, 0xd2, 0x8a, 0x47, 0xe8, 0x1b, 0xb5, 0xcf, 0xd3, 0x17, 0xa9, 0xe2,
	0x04, 0xda, 0x40, 0x1b, 0xae, 0xda, 0x9b, 0x44, 0xe7, 0x3f, 0x27, 0x27, 0xbf, 0xff, 0x4f, 0x46,
	0x5f, 0x59, 0x1c, 0xc5, 0xb1, 0xc8, 0x79, 0x46, 0xa5, 0x12, 0x99, 0x98, 0x99, 0xa7, 0xdf, 0xab,
	0x89, 0x93, 0xbb, 0x16, 0x1a, 0x86, 0x2b, 0xba, 0x08, 0x28, 0x81, 0x6b, 0x02, 0x9b, 0x44, 0x67,
	0xa0, 0xe6, 0xc5, 0x48, 0xf6, 0x57, 0x6f, 0xfc, 0x21, 0x72, 0x73, 0x0d, 0x8a, 0x47, 0x29, 0x60,
	0x6b, 0x6c, 0x4d, 0x3d, 0xb2, 0xaf, 0x8b, 0x9e, 0x8c, 0xb4, 0xbe, 0x15, 0x8a, 0xe1, 0x56, 0xd9,
	0xdb, 0xd5, 0xfe, 0x0f, 0xf4, 0x29, 0xbe, 0x4a, 0x80, 0x67, 0x34, 0xdb, 0x4a, 0xc0, 0xed, 0xb1,
	0x35, 0xed, 0x11, 0x54, 0x4a, 0x67, 0x5b, 0x09, 0xfe, 0x77, 0xe4, 0xc9, 0x4b, 0xc1, 0x81, 0xf2,
	0x3c, 0xc5, 0xb6, 0x69, 0xbb, 0x46, 0xf8, 0x97, 0xa7, 0xfe, 0x4f, 0xd4, 0xab, 0xbe, 0x8e, 0x05,
	0xe7, 0xcb, 0x05, 0xee, 0x9a, 0x81, 0xcf, 0xa5, 0x18, 0x18, 0xad, 0xd8, 0x50, 0x0d, 0x25, 0x12,
	0x3b, 0xe5, 0xff, 0x4b, 0x61, 0x29, 0xfd, 0x01, 0x72, 0xd3, 0x28, 0xa6, 0x11, 0x63, 0x0a, 0xbb,
	0xa6, 0xe7, 0xa4, 0x51, 0x3c, 0x67, 0x4c, 0xf9, 0x18, 0x39, 0x37, 0xa0, 0x74, 0x22, 0x38, 0xf6,
	0xcc, 0xda, 0x5d, 0x39, 0x79, 0xb0, 0xd0, 0x68, 0x11, 0xd0, 0x70, 0x45, 0x09, 0x68, 0xc9, 0x8f,
	0xd3, 0x38, 0xf2, 0x65, 0xbd, 0xee, 0x4b, 0x81, 0x2e, 0x46, 0x18, 0x98, 0x5c, 0x3a, 0xc4, 0x2d,
	0x84, 0x40, 0x30, 0xa8, 0xe5, 0xd9, 0x6e, 0xc8, 0xd3, 0x6e, 0xce, 0xb3, 0x73, 0x98, 0xe7, 0xe4,
	0xd1, 0x42, 0xfd, 0x3d, 0xc7, 0x50, 0x6c, 0x12, 0xfe, 0xae, 0xf8, 0x8e, 0x92, 0xb0, 0x4f, 0x11,
	0xea, 0x34, 0x10, 0xea, 0xbe, 0x49, 0xc8, 0xa9, 0x13, 0xba, 0xb7, 0xd0, 0xe0, 0x05, 0x21, 0x73,
	0xce, 0x8f, 0xc2, 0x33, 0x42, 0x5e, 0x75, 0x75, 0xaa, 0xe3, 0xda, 0xe4, 0x59, 0x38, 0x0d, 0x88,
	0xa0, 0x6f, 0x25, 0x9f, 0xc0, 0x68, 0xff, 0xd7, 0xeb, 0x30, 0xe1, 0x50, 0xd8, 0xae, 0x2d, 0x6e,
	0x1d, 0x2e, 0x6e, 0xb0, 0xf4, 0xa7, 0x7f, 0xfe, 0x65, 0xf6, 0xab, 0x76, 0x9f, 0x2f, 0xba, 0xe6,
	0xf5, 0xfb, 0x29, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x1d, 0xc1, 0x67, 0xfe, 0x03, 0x00, 0x00,
}
