// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datacenter.proto

package dc_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//服务器信息
type ServerInfoMsg struct {
	AppId                int32    `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppKind              int32    `protobuf:"varint,2,opt,name=app_kind,json=appKind,proto3" json:"app_kind,omitempty"`
	OutAddr              string   `protobuf:"bytes,4,opt,name=out_addr,json=outAddr,proto3" json:"out_addr,omitempty"`
	OutProt              string   `protobuf:"bytes,5,opt,name=out_prot,json=outProt,proto3" json:"out_prot,omitempty"`
	Account_ID           uint32   `protobuf:"varint,6,opt,name=account_ID,json=accountID,proto3" json:"account_ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfoMsg) Reset()         { *m = ServerInfoMsg{} }
func (m *ServerInfoMsg) String() string { return proto.CompactTextString(m) }
func (*ServerInfoMsg) ProtoMessage()    {}
func (*ServerInfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{0}
}

func (m *ServerInfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfoMsg.Unmarshal(m, b)
}
func (m *ServerInfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfoMsg.Marshal(b, m, deterministic)
}
func (m *ServerInfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfoMsg.Merge(m, src)
}
func (m *ServerInfoMsg) XXX_Size() int {
	return xxx_messageInfo_ServerInfoMsg.Size(m)
}
func (m *ServerInfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfoMsg proto.InternalMessageInfo

func (m *ServerInfoMsg) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *ServerInfoMsg) GetAppKind() int32 {
	if m != nil {
		return m.AppKind
	}
	return 0
}

func (m *ServerInfoMsg) GetOutAddr() string {
	if m != nil {
		return m.OutAddr
	}
	return ""
}

func (m *ServerInfoMsg) GetOutProt() string {
	if m != nil {
		return m.OutProt
	}
	return ""
}

func (m *ServerInfoMsg) GetAccount_ID() uint32 {
	if m != nil {
		return m.Account_ID
	}
	return 0
}

//返回注册信息并同步时间
type RespnRegisterServerInfoMsg struct {
	RestCode             int32    `protobuf:"varint,1,opt,name=rest_code,json=restCode,proto3" json:"rest_code,omitempty"`
	UnixNano             int64    `protobuf:"varint,2,opt,name=unix_nano,json=unixNano,proto3" json:"unix_nano,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespnRegisterServerInfoMsg) Reset()         { *m = RespnRegisterServerInfoMsg{} }
func (m *RespnRegisterServerInfoMsg) String() string { return proto.CompactTextString(m) }
func (*RespnRegisterServerInfoMsg) ProtoMessage()    {}
func (*RespnRegisterServerInfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{1}
}

func (m *RespnRegisterServerInfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespnRegisterServerInfoMsg.Unmarshal(m, b)
}
func (m *RespnRegisterServerInfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespnRegisterServerInfoMsg.Marshal(b, m, deterministic)
}
func (m *RespnRegisterServerInfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespnRegisterServerInfoMsg.Merge(m, src)
}
func (m *RespnRegisterServerInfoMsg) XXX_Size() int {
	return xxx_messageInfo_RespnRegisterServerInfoMsg.Size(m)
}
func (m *RespnRegisterServerInfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RespnRegisterServerInfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RespnRegisterServerInfoMsg proto.InternalMessageInfo

func (m *RespnRegisterServerInfoMsg) GetRestCode() int32 {
	if m != nil {
		return m.RestCode
	}
	return 0
}

func (m *RespnRegisterServerInfoMsg) GetUnixNano() int64 {
	if m != nil {
		return m.UnixNano
	}
	return 0
}

//返回心跳消息
type RespnServerHeartBeatMsg struct {
	RestCode             int32    `protobuf:"varint,1,opt,name=rest_code,json=restCode,proto3" json:"rest_code,omitempty"`
	UnixNano             int64    `protobuf:"varint,2,opt,name=unix_nano,json=unixNano,proto3" json:"unix_nano,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespnServerHeartBeatMsg) Reset()         { *m = RespnServerHeartBeatMsg{} }
func (m *RespnServerHeartBeatMsg) String() string { return proto.CompactTextString(m) }
func (*RespnServerHeartBeatMsg) ProtoMessage()    {}
func (*RespnServerHeartBeatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{2}
}

func (m *RespnServerHeartBeatMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespnServerHeartBeatMsg.Unmarshal(m, b)
}
func (m *RespnServerHeartBeatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespnServerHeartBeatMsg.Marshal(b, m, deterministic)
}
func (m *RespnServerHeartBeatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespnServerHeartBeatMsg.Merge(m, src)
}
func (m *RespnServerHeartBeatMsg) XXX_Size() int {
	return xxx_messageInfo_RespnServerHeartBeatMsg.Size(m)
}
func (m *RespnServerHeartBeatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RespnServerHeartBeatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RespnServerHeartBeatMsg proto.InternalMessageInfo

func (m *RespnServerHeartBeatMsg) GetRestCode() int32 {
	if m != nil {
		return m.RestCode
	}
	return 0
}

func (m *RespnServerHeartBeatMsg) GetUnixNano() int64 {
	if m != nil {
		return m.UnixNano
	}
	return 0
}

//服务器信息
type ServerInfoToUserMsg struct {
	Serverinfo           *ServerInfoMsg `protobuf:"bytes,1,opt,name=serverinfo,proto3" json:"serverinfo,omitempty"`
	Account_ID           uint64         `protobuf:"varint,2,opt,name=account_ID,json=accountID,proto3" json:"account_ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ServerInfoToUserMsg) Reset()         { *m = ServerInfoToUserMsg{} }
func (m *ServerInfoToUserMsg) String() string { return proto.CompactTextString(m) }
func (*ServerInfoToUserMsg) ProtoMessage()    {}
func (*ServerInfoToUserMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{3}
}

func (m *ServerInfoToUserMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfoToUserMsg.Unmarshal(m, b)
}
func (m *ServerInfoToUserMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfoToUserMsg.Marshal(b, m, deterministic)
}
func (m *ServerInfoToUserMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfoToUserMsg.Merge(m, src)
}
func (m *ServerInfoToUserMsg) XXX_Size() int {
	return xxx_messageInfo_ServerInfoToUserMsg.Size(m)
}
func (m *ServerInfoToUserMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfoToUserMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfoToUserMsg proto.InternalMessageInfo

func (m *ServerInfoToUserMsg) GetServerinfo() *ServerInfoMsg {
	if m != nil {
		return m.Serverinfo
	}
	return nil
}

func (m *ServerInfoToUserMsg) GetAccount_ID() uint64 {
	if m != nil {
		return m.Account_ID
	}
	return 0
}

//服务器系统信息 发送心跳的时候上报
type ServerSysInfo struct {
	FromAppId            int32    `protobuf:"varint,1,opt,name=from_app_id,json=fromAppId,proto3" json:"from_app_id,omitempty"`
	UserConnnum          int32    `protobuf:"varint,2,opt,name=user_connnum,json=userConnnum,proto3" json:"user_connnum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerSysInfo) Reset()         { *m = ServerSysInfo{} }
func (m *ServerSysInfo) String() string { return proto.CompactTextString(m) }
func (*ServerSysInfo) ProtoMessage()    {}
func (*ServerSysInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{4}
}

func (m *ServerSysInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerSysInfo.Unmarshal(m, b)
}
func (m *ServerSysInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerSysInfo.Marshal(b, m, deterministic)
}
func (m *ServerSysInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerSysInfo.Merge(m, src)
}
func (m *ServerSysInfo) XXX_Size() int {
	return xxx_messageInfo_ServerSysInfo.Size(m)
}
func (m *ServerSysInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerSysInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerSysInfo proto.InternalMessageInfo

func (m *ServerSysInfo) GetFromAppId() int32 {
	if m != nil {
		return m.FromAppId
	}
	return 0
}

func (m *ServerSysInfo) GetUserConnnum() int32 {
	if m != nil {
		return m.UserConnnum
	}
	return 0
}

//关闭远端客户端连接
type CloseClientLinkMsg struct {
	AccountId            uint64   `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseClientLinkMsg) Reset()         { *m = CloseClientLinkMsg{} }
func (m *CloseClientLinkMsg) String() string { return proto.CompactTextString(m) }
func (*CloseClientLinkMsg) ProtoMessage()    {}
func (*CloseClientLinkMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{5}
}

func (m *CloseClientLinkMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseClientLinkMsg.Unmarshal(m, b)
}
func (m *CloseClientLinkMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseClientLinkMsg.Marshal(b, m, deterministic)
}
func (m *CloseClientLinkMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseClientLinkMsg.Merge(m, src)
}
func (m *CloseClientLinkMsg) XXX_Size() int {
	return xxx_messageInfo_CloseClientLinkMsg.Size(m)
}
func (m *CloseClientLinkMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseClientLinkMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CloseClientLinkMsg proto.InternalMessageInfo

func (m *CloseClientLinkMsg) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerInfoMsg)(nil), "datacenter_proto.ServerInfoMsg")
	proto.RegisterType((*RespnRegisterServerInfoMsg)(nil), "datacenter_proto.RespnRegisterServerInfoMsg")
	proto.RegisterType((*RespnServerHeartBeatMsg)(nil), "datacenter_proto.RespnServerHeartBeatMsg")
	proto.RegisterType((*ServerInfoToUserMsg)(nil), "datacenter_proto.ServerInfoToUserMsg")
	proto.RegisterType((*ServerSysInfo)(nil), "datacenter_proto.ServerSysInfo")
	proto.RegisterType((*CloseClientLinkMsg)(nil), "datacenter_proto.CloseClientLinkMsg")
}

func init() { proto.RegisterFile("datacenter.proto", fileDescriptor_f3733bc645feed7a) }

var fileDescriptor_f3733bc645feed7a = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x15, 0xd8, 0x76, 0x9b, 0xe9, 0xae, 0x84, 0x82, 0x10, 0x01, 0x04, 0x94, 0x9c, 0x7a,
	0x0a, 0x12, 0xfb, 0x01, 0xd0, 0x6e, 0xf6, 0x40, 0xc4, 0x1f, 0x21, 0x17, 0x38, 0x70, 0xb1, 0x4c,
	0x3c, 0x5d, 0x59, 0xdb, 0xce, 0x58, 0xb6, 0x83, 0xe0, 0x8b, 0xf0, 0x79, 0x91, 0xdd, 0x14, 0xd2,
	0x5e, 0xf7, 0x64, 0xe9, 0xf7, 0xe4, 0x37, 0x6f, 0xe6, 0xc1, 0x03, 0xad, 0x82, 0xea, 0x90, 0x02,
	0xba, 0xda, 0x3a, 0x0e, 0x5c, 0x8c, 0x88, 0x4c, 0xa4, 0xfa, 0x93, 0xc1, 0xf9, 0x0a, 0xdd, 0x4f,
	0x74, 0x2d, 0xad, 0xf9, 0xa3, 0xbf, 0x29, 0x1e, 0xc1, 0x54, 0x59, 0x2b, 0x8d, 0x2e, 0xb3, 0x45,
	0xb6, 0x9c, 0x88, 0x89, 0xb2, 0xb6, 0xd5, 0xc5, 0x13, 0x98, 0x45, 0x7c, 0x6b, 0x48, 0x97, 0xf7,
	0x92, 0x70, 0xaa, 0xac, 0x7d, 0x6f, 0x28, 0x49, 0xdc, 0x07, 0xa9, 0xb4, 0x76, 0xe5, 0xc9, 0x22,
	0x5b, 0xe6, 0xe2, 0x94, 0xfb, 0x70, 0xa9, 0xb5, 0xdb, 0x4b, 0x71, 0x56, 0x39, 0xf9, 0x27, 0x7d,
	0x76, 0x1c, 0x8a, 0xe7, 0x00, 0xaa, 0xeb, 0xb8, 0xa7, 0x20, 0xdb, 0xeb, 0x72, 0xba, 0xc8, 0x96,
	0xe7, 0x22, 0x1f, 0x48, 0x7b, 0x5d, 0x7d, 0x83, 0xa7, 0x02, 0xbd, 0x25, 0x81, 0x37, 0xc6, 0x07,
	0x74, 0x87, 0x21, 0x9f, 0x41, 0xee, 0xd0, 0x07, 0xd9, 0xb1, 0xc6, 0x21, 0xe7, 0x2c, 0x82, 0x86,
	0x35, 0x46, 0xb1, 0x27, 0xf3, 0x4b, 0x92, 0x22, 0x4e, 0x59, 0xef, 0x8b, 0x59, 0x04, 0x9f, 0x14,
	0x71, 0xb5, 0x82, 0xc7, 0xc9, 0x77, 0xe7, 0xf7, 0x0e, 0x95, 0x0b, 0x57, 0xa8, 0xc2, 0xdd, 0x4c,
	0x7b, 0x78, 0xf8, 0x3f, 0xdf, 0x17, 0xfe, 0xea, 0xd1, 0x45, 0xc3, 0xb7, 0x00, 0x3e, 0x61, 0x43,
	0x6b, 0x4e, 0x8e, 0xf3, 0x37, 0x2f, 0xeb, 0xe3, 0x0e, 0xea, 0x83, 0xd5, 0xc4, 0xe8, 0xcb, 0xd1,
	0x8d, 0xe2, 0xd4, 0x93, 0xf1, 0x8d, 0xc4, 0xbe, 0xbb, 0xd5, 0x6f, 0x1f, 0xbf, 0x17, 0x2f, 0x60,
	0xbe, 0x76, 0xbc, 0x95, 0x07, 0x05, 0xe6, 0x11, 0x5d, 0xa6, 0x12, 0x5f, 0xc1, 0x59, 0xef, 0xd1,
	0xc9, 0x8e, 0x89, 0xa8, 0xdf, 0x0e, 0x45, 0xce, 0x23, 0x6b, 0x76, 0xa8, 0xba, 0x80, 0xa2, 0xd9,
	0xb0, 0xc7, 0x66, 0x63, 0x90, 0xc2, 0x07, 0x43, 0xb7, 0x71, 0x93, 0x51, 0x90, 0xc1, 0x77, 0x14,
	0x44, 0x5f, 0x9d, 0x7d, 0x87, 0xfa, 0xb5, 0xee, 0x76, 0xfb, 0xfc, 0x98, 0xa6, 0xe7, 0xe2, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x71, 0xa0, 0x0e, 0x80, 0x02, 0x00, 0x00,
}
