// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package common_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//空消息共用
type NullMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullMsg) Reset()         { *m = NullMsg{} }
func (m *NullMsg) String() string { return proto.CompactTextString(m) }
func (*NullMsg) ProtoMessage()    {}
func (*NullMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *NullMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullMsg.Unmarshal(m, b)
}
func (m *NullMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullMsg.Marshal(b, m, deterministic)
}
func (m *NullMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullMsg.Merge(m, src)
}
func (m *NullMsg) XXX_Size() int {
	return xxx_messageInfo_NullMsg.Size(m)
}
func (m *NullMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NullMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NullMsg proto.InternalMessageInfo

//结果码
type RestInt32CodeMsg struct {
	RestCode             int32    `protobuf:"varint,1,opt,name=rest_code,json=restCode,proto3" json:"rest_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestInt32CodeMsg) Reset()         { *m = RestInt32CodeMsg{} }
func (m *RestInt32CodeMsg) String() string { return proto.CompactTextString(m) }
func (*RestInt32CodeMsg) ProtoMessage()    {}
func (*RestInt32CodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *RestInt32CodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestInt32CodeMsg.Unmarshal(m, b)
}
func (m *RestInt32CodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestInt32CodeMsg.Marshal(b, m, deterministic)
}
func (m *RestInt32CodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestInt32CodeMsg.Merge(m, src)
}
func (m *RestInt32CodeMsg) XXX_Size() int {
	return xxx_messageInfo_RestInt32CodeMsg.Size(m)
}
func (m *RestInt32CodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RestInt32CodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RestInt32CodeMsg proto.InternalMessageInfo

func (m *RestInt32CodeMsg) GetRestCode() int32 {
	if m != nil {
		return m.RestCode
	}
	return 0
}

func init() {
	proto.RegisterType((*NullMsg)(nil), "common_proto.NullMsg")
	proto.RegisterType((*RestInt32CodeMsg)(nil), "common_proto.RestInt32CodeMsg")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x82, 0xf2, 0xe2, 0xc1, 0x3c, 0x25, 0x4e,
	0x2e, 0x76, 0xbf, 0xd2, 0x9c, 0x1c, 0xdf, 0xe2, 0x74, 0x25, 0x7d, 0x2e, 0x81, 0xa0, 0xd4, 0xe2,
	0x12, 0xcf, 0xbc, 0x12, 0x63, 0x23, 0xe7, 0xfc, 0x94, 0x54, 0xdf, 0xe2, 0x74, 0x21, 0x69, 0x2e,
	0xce, 0xa2, 0xd4, 0xe2, 0x92, 0xf8, 0xe4, 0xfc, 0x94, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6,
	0x20, 0x0e, 0x90, 0x00, 0x48, 0xde, 0x49, 0x20, 0x8a, 0x4f, 0x4f, 0x1f, 0xd9, 0xb4, 0x24, 0x36,
	0x30, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x84, 0x64, 0x80, 0x72, 0x00, 0x00, 0x00,
}
